// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uuvizhfakduuxvquvsoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1dml6aGZha2R1dXh2cXV2c29oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1Mzk5MDEsImV4cCI6MjA2NDExNTkwMX0.9iuirOn9Y-UjmMzTdl1KrrAV_Tdd6OP2wjX_Ab9yp1Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

//dbpziRbyz-heffah-nojno2

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);